version: '3'
services:
  app:
    image: cleydyr/biblivre:5.2.0-cloud
    ports:
    - "$APP_HTTP_HOST_PORT:8080"
    - "$APP_DEBUG_HOST_PORT:8000"
    environment:
    - "JAVA_OPTS=\"-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n\""
    - "DATABASE_HOST_NAME=$DATABASE_HOST_NAME"
    - "DATABASE_PORT=5432"
    - "PGUSER=$POSTGRES_USER"
    - "PGPASSWORD=$POSTGRES_PASSWORD"
    - "PGDATABASE=$POSTGRES_DB"
    depends_on:
    - database
    command: sh -c 'wait-for.sh -t 60 $$DATABASE_HOST_NAME:$$DATABASE_PORT -- /usr/local/tomcat/bin/catalina.sh run'

  database:
    hostname: $DATABASE_HOST_NAME
    image: postgres
    ports:
    - "$DATABASE_HOST_PORT:5432"
    volumes:
    - "./sql/biblivre4.sql:/docker-entrypoint-initdb.d/populate-initial-data.sql"
    environment:
    - "POSTGRES_USER=$POSTGRES_USER"
    - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    - "POSTGRES_DB=$POSTGRES_DB"

